# mongodb001ser.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: chochanguk/k8s_yoribogo_boot # 도커허브의 내 서버 이미지
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
