apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWFyaWRi  # base64로 인코딩된 'mariadb'
  MYSQL_DATABASE: eW9yaWJvZ2Ri  # base64로 인코딩된 'yoribogodb'
  MYSQL_USER: eW9yaWJvZ28=  # base64로 인코딩된 'yoribogo'
  MYSQL_PASSWORD: eW9yaWJvZ28=  # base64로 인코딩된 'yoribogo'
